name: SwiftTorch
options:
  bundleIdPrefix: com.swiftTorch

targets:
  SwiftTorch:
    type: tool
    platform: macOS
    deploymentTarget: "10.13"
    sources: 
        - Sources
    dependencies:
      - framework: /Library/Developer/Toolchains/swift-latest/usr/lib/swift/macosx/libtensorflow_framework.so
      - framework: /Library/Developer/Toolchains/swift-latest/usr/lib/swift/macosx/libtensorflow.so
      - framework: libpython2.7.tbd
    SWIFT_OPTIMIZATION_LEVEL: -O
    LD_RUNPATH_SEARCH_PATHS: "/Library/Developer/Toolchains/swift-latest/usr/lib/swift/macosx"
    OTHER_LDFLAGS:  -lpython
    
schemes:
  SwiftTorch:
    build:
      parallelizeBuild: true
      buildImplicitDependencies: true
      targets:
        SwiftTorch: all
    run:
      targets:
        SwiftTorch: all
      preActions:
        - script: conda activate gymai2
          settingsTarget: SwiftTorch